### ISSUE TITLE
Encontrar o arquivo da anotação relacionado ao pdf aberto no mesmo diretório.

### ISSUE THREAD

**Issue by luanhcastro** [luanhcastro/xournalpp#2]
## História: 
* Como professor, eu gostaria de encontrar o arquivo de notação relacionado ao pdf aberto no mesmo diretório automaticamente de forma mais ágil.

## Critérios de aceitação: 
* Ao abrir um pdf no Xournal , o sistema deve buscar o  arquivo de anotação relacionado no mesmo diretório. Caso não encontre, ele deve tentar encontrar algum  arquivo de anotação existente no diretório com o nome similar.

* Caso mais de um  arquivo de anotação como nome similar seja encontrado o software deve ranqueá- los e possibilitar a escolha correta.

**Comment by magsilva** [comment]
Alguns pontos que observei a ausência:
- quantidade de pontos da história (indicar como um rótulo ao invés de texto no comentário);
- rótulo (label), indicando que é uma história de usuário.

Quanto à especificação da história do usuário, a redação da parte do benefício não ficou clara. Talvez seja uma questão de ajuste na parte "de forma mais ágil": "para que eu inicie a leitura e anotação de forma mais ágil".

**Comment by luanhcastro** [comment]
Dividida entre as issues 12 e 13.
